### ISSUE TITLE
 Failed to validate your Udacity token.

### ISSUE THREAD

**Issue by japisingh** [udacimak/udacimak#192]
**Describe the bug**
Hi,
Both using Method 1 (login: username and password) and Method 2 (settoken), I am getting the following error:
✖ Validate Udacity authentication token via Udacity API
 2021-03-01T17:29:19.377Z [error]: Failed to validate your Udacity token. Please try again. Here's the error message:             [                                                                                                                                    { "message": "Unknown argument \"include_free_preview\" on field \"nanodegrees\" of type \"User\".",
"status": null  },
{"message": "Cannot query field \"version_upgrade_details\" on type \"Nanodegree\".",
 "status": null                                                                                                               }
 ]  

**To Reproduce**
1. login by "udacimak login"
2. type username and password

**Expected behavior**
The expectation was that the token or login will be validated

**Udacimak Log**
no .log file was found

```shell
INSERT_LOG_HERE
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 through WSL2 Windows 10
 - Node version: 14.7.0
 - npm version: 6.14.7
 - Udacimak Version: 1.6.6
 - Browser :chrome

**Course Information**
 - Nanodegree or Course name: [Data Analyst Nanodegree]
 - Version: 
 - Locale: en-us

**Comment by VeneratioVitae** [comment]
I'm having the exact same issue !

**Comment by yogesh-sirsat** [comment]
i am facing same problem

**Comment by amoat7** [comment]
facing the same problem

**Comment by chinmaydas96** [comment]
having same issue any solution here

**Comment by KSanjayReddy** [comment]
observing the same issue, kindly look into it

**Comment by josancamon19** [comment]
Same here

**Comment by amoat7** [comment]
i was finally able to fix mine. It seems the schema for the udacity api as changed. You need to locate the udacimak library installed on your pc. go into the api folder, search through the files and delete any fields that throw an error. 

For login that will be "fetchUdacityUserInfo.js"

I'm using windows and the api files are located in this folder: "~\Continuum\anaconda3\node_modules\udacimak\lib\api"

**Comment by chinmaydas96** [comment]
@amoat7 yes it works, at least login successful.
This is the updated file.



"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.default = fetchUdacityUserInfo;

var _config = require("../config");

var _ = require(".");

/**
 * Fetch User information from Udacity API
 * @param {string} udacityAuthToken Udacity authentication token
 */
function fetchUdacityUserInfo(udacityAuthToken) {
    const queryGraphql = '{"query":"\\n    query UserBaseQuery {\\n      user {\\n        id\\n        first_name\\n        last_name\\n        email\\n        nickname\\n        preferred_language\\n        affiliate_program_key\\n        can_see_professional_profile\\n        can_edit_content\\n        \\n  email_preferences {\\n    receive_marketing\\n  }\\n\\n        \\n  settings {\\n    skip_classroom_welcome\\n    dismissed_upgrade_ids\\n    onboarding_completed_keys\\n  }\\n\\n        social_logins {\\n          provider\\n          id\\n        }\\n        user_tags {\\n          namespace\\n          tag\\n        }\\n        nanodegrees(start_index: 0, is_graduated: false) {\\n          id\\n          key\\n          title\\n          locale\\n          version\\n          semantic_type\\n                    user_state {\\n            last_viewed_at\\n          }\\n        }\\n        graduated_nanodegrees: nanodegrees(is_graduated: true) {\\n          id\\n          key\\n          locale\\n          version\\n        }\\n        courses(start_index: 0, is_graduated: false) {\\n          id\\n          key\\n          title\\n          locale\\n          version\\n          semantic_type\\n          user_state {\\n            last_viewed_at\\n          }\\n        }\\n        graduated_courses: courses(is_graduated: true) {\\n          id\\n          key\\n          locale\\n          version\\n        }\\n      }\\n    }\\n  ","variables":null,"locale":"en-us"}';
    return (0, _.fetchApiUdacityGraphql)(_config.API_ENDPOINTS_UDACITY_GRAPHQL, queryGraphql, udacityAuthToken);
}

**Comment by chinmaydas96** [comment]
@amoat7 did you change all the files, if yes can you share the files? Cant download after login also.

**Comment by amoat7** [comment]
Hi guys replace the files in your ~\node_modules\udacimak\lib\api folder with these files ([api.zip](https://github.com/udacimak/udacimak/files/6087914/api.zip)). You will have to find a way to locate your node modules folder as it differs for most systems. I made changes to the code and they work fine for me. You can first make a backup of your old files before replacing.

**Comment by chinmaydas96** [comment]
sure thanks so far it is working for me.

**Comment by FadyMorris** [comment]
Thank you so much @amoat7 . I replaced the files in `api` directory with your uploaded files and they worked perfectly !

**Comment by leandro-marcelino** [comment]
@amoat7, thank you so much!

**Comment by fisal77** [comment]
> Hi guys replace the files in your ~\node_modules\udacimak\lib\api folder with these files ([api.zip](https://github.com/udacimak/udacimak/files/6087914/api.zip)). You will have to find a way to locate your node modules folder as it differs for most systems. I made changes to the code and they work fine for me. You can first make a backup of your old files before replacing.

Yes it's solved.... Thanks @amoat7

**Comment by SJ029626** [comment]
Yes definitely that solved the issue Thanks @amoat7

**Comment by dembeckh** [comment]
Thanks a lot, @amoat7.

**Comment by GhaziXX** [comment]
hey @amoat7, can you please provide us any hint on how to install udacimak, as it's not installing any more?

![image](https://user-images.githubusercontent.com/24620184/116125064-f76b5100-a6bc-11eb-9aa7-79c310f93b3d.png)

**Comment by maximshepin** [comment]
doesn't work for me tried today.  I think they changed the response structure again.
Anyone tried recently?

**Comment by nenericamarius** [comment]
> Hi guys replace the files in your ~\node_modules\udacimak\lib\api folder with these files ([api.zip](https://github.com/udacimak/udacimak/files/6087914/api.zip)). You will have to find a way to locate your node modules folder as it differs for most systems. I made changes to the code and they work fine for me. You can first make a backup of your old files before replacing.

You are awesome!

**Comment by grupobancamovilmt** [comment]
> doesn't work for me tried today. I think they changed the response structure again.
> Anyone tried recently?

i have the same issue

**Comment by jatobrun** [comment]
> > Hi guys replace the files in your ~\node_modules\udacimak\lib\api folder with these files ([api.zip](https://github.com/udacimak/udacimak/files/6087914/api.zip)). You will have to find a way to locate your node modules folder as it differs for most systems. I made changes to the code and they work fine for me. You can first make a backup of your old files before replacing.
> 
> You are awesome!
 
Do you resolve the problem?

**Comment by nenericamarius** [comment]
> > > Hi guys replace the files in your ~\node_modules\udacimak\lib\api folder with these files ([api.zip](https://github.com/udacimak/udacimak/files/6087914/api.zip)). You will have to find a way to locate your node modules folder as it differs for most systems. I made changes to the code and they work fine for me. You can first make a backup of your old files before replacing.
> > 
> > 
> > You are awesome!
> 
> Do you resolve the problem?

Yes @jayobrun it works!!
(in Windows dir is C:\Users\YOUR_USER\AppData\Roaming\npm\node_modules\udacimak)

**Comment by nenericamarius** [comment]
> hey @amoat7, can you please provide us any hint on how to install udacimak, as it's not installing any more?
> 
> ![image](https://user-images.githubusercontent.com/24620184/116125064-f76b5100-a6bc-11eb-9aa7-79c310f93b3d.png)

@GhaziXX first uninstall python (you can reinstall later), after that in terminal npm remove -g udacimak && remove -g youtube-dl && npm install -g udacimak

**Comment by rohitsathish** [comment]
> > hey @amoat7, can you please provide us any hint on how to install udacimak, as it's not installing any more?
> > ![image](https://user-images.githubusercontent.com/24620184/116125064-f76b5100-a6bc-11eb-9aa7-79c310f93b3d.png)
> 
> @GhaziXX first uninstall python (you can reinstall later), after that in terminal npm remove -g udacimak && remove -g youtube-dl && npm install -g udacimak

@nenericamarius Tried this, doesn't work. Produces the same errors after removing Python.

**Comment by nenericamarius** [comment]
> > > hey @amoat7, can you please provide us any hint on how to install udacimak, as it's not installing any more?
> > > ![image](https://user-images.githubusercontent.com/24620184/116125064-f76b5100-a6bc-11eb-9aa7-79c310f93b3d.png)
> > 
> > @GhaziXX first uninstall python (you can reinstall later), after that in terminal npm remove -g udacimak && remove -g youtube-dl && npm install -g udacimak
> 
> @nenericamarius Tried this, doesn't work. Produces the same errors after removing Python.

Delete in your user director node_modules and package-lock.json then npm update

**Comment by Eslam-Abdo** [comment]
> hey @amoat7, can you please provide us any hint on how to install udacimak, as it's not installing any more?
> 
> ![image](https://user-images.githubusercontent.com/24620184/116125064-f76b5100-a6bc-11eb-9aa7-79c310f93b3d.png)

try use 
 ``` sudo npm install -g udacimak ``` 
OR
``` sudo npm install -g udacimak --unsafe-perm=true --allow-root ```
instant of 
``` npm install -g udacimak ```

and if no error appear use this command to check that udacimak is install well 
``` udacimak --version ``` OR ``` sudo udacimak --version ```

NOTE: I TRY  THIS COMMAND ON (ubentu 20) AND IT WORK IF  YOU USE (windows) I THINK IT GIVE YOU ERROR  LIKE no sudo

**Comment by rohitsathish** [comment]
> > > > hey @amoat7, can you please provide us any hint on how to install udacimak, as it's not installing any more?
> > > > ![image](https://user-images.githubusercontent.com/24620184/116125064-f76b5100-a6bc-11eb-9aa7-79c310f93b3d.png)
> > > 
> > > 
> > > @GhaziXX first uninstall python (you can reinstall later), after that in terminal npm remove -g udacimak && remove -g youtube-dl && npm install -g udacimak
> > 
> > 
> > @nenericamarius Tried this, doesn't work. Produces the same errors after removing Python.
> 
> Delete in your user directory the dir "node_modules" and file "package-lock.json". After that execute: npm install

@nenericamarius Thanks for your input. But since the installation fails, it doesn't create a udacimak folder in node_modules. And even if you remove package-lock.json, it will throw up an error since it doesn't know where to load the packages from.

But I'm a novice with npm and node, maybe I misunderstood what you're saying.

**Comment by jatobrun** [comment]
Try to install with yarn

Sent from my iPhone

On May 3, 2021, at 8:46 AM, Rohit ***@***.***> wrote:

﻿

hey @amoat7<https://github.com/amoat7>, can you please provide us any hint on how to install udacimak, as it's not installing any more?
[image]<https://user-images.githubusercontent.com/24620184/116125064-f76b5100-a6bc-11eb-9aa7-79c310f93b3d.png>

@GhaziXX<https://github.com/GhaziXX> first uninstall python (you can reinstall later), after that in terminal npm remove -g udacimak && remove -g youtube-dl && npm install -g udacimak

@nenericamarius<https://github.com/nenericamarius> Tried this, doesn't work. Produces the same errors after removing Python.

Delete in your user directory the dir "node_modules" and file "package-lock.json". After that execute: npm install

@nenericamarius<https://github.com/nenericamarius> Thanks for your input. But since the installation fails, it doesn't create a udacimak folder in node_modules. And even if you remove package-lock.json, it will throw up an error since it doesn't know where to load the packages from.

But I'm a novice with npm and node, maybe I misunderstood what you're saying.

**Comment by maximshepin** [comment]
maksimshepin@Maksims-MacBook-Pro ~ % udacimak login
? Email: 
? Password: [hidden]
✖ Validate Udacity authentication token via Udacity API
2021-05-03T23:46:43.051Z [error]: Failed to validate your Udacity token. Please try again. Here's the error message:
[
    {
        "message": "Unknown argument \"include_free_preview\" on field \"nanodegrees\" of type \"User\".",
        "status": null
    },
    {
        "message": "Cannot query field \"version_upgrade_details\" on type \"Nanodegree\".",
        "status": null
    }
]
maksimshepin@Maksims-MacBook-Pro ~ % 




no luck after replacing all files in API folder - same error - please help

**Comment by mmphego** [comment]
> Hi guys replace the files in your ~\node_modules\udacimak\lib\api folder with these files ([api.zip](https://github.com/udacimak/udacimak/files/6087914/api.zip)). You will have to find a way to locate your node modules folder as it differs for most systems. I made changes to the code and they work fine for me. You can first make a backup of your old files before replacing.

Please create a PR for this fix please or fork

**Comment by dishantTanwar** [comment]
> Hi guys replace the files in your ~\node_modules\udacimak\lib\api folder with these files ([api.zip](https://github.com/udacimak/udacimak/files/6087914/api.zip)). You will have to find a way to locate your node modules folder as it differs for most systems. I made changes to the code and they work fine for me. You can first make a backup of your old files before replacing.

It worked for me. Thank you so much

**Comment by maximshepin** [comment]
no luck after replacing all files in API folder - same error - please help

**Comment by fmorelli89** [comment]
For dependencies errors, I'm using udacimak/udacimak container. The issue I had they are similar which you mentioned.
The problems re:
1) Change Output rest API for getting Auth Token, by Udacity
2) It needs to update youtube-dl to download video

For a docker instance, but the steps are similar for on-premise installation (use your path)

docker pull udacimak/udacimak
docker container run --rm -it -v "$(pwd)/:/downloads" --entrypoint /bin/bash udacimak/udacimak 

inside container's cli
apt-get update
apt-get install wget unzip

 -- UPDTATE REST API -- OVERWRITE
wget https://github.com/udacimak/udacimak/files/6087914/api.zip
unzip api.zip -d /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/lib/api/ 

--UPDATE youtube-dl
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl
chmod a+rx /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl

**Comment by anikchowdhury1** [comment]
Same here, no luck after replacing all files in the API folder - same error! Please help!

**Comment by SJ029626** [comment]
Guys the workaround is instead of replacing the api.zip replace in the node module, here is the directory that I have used and it will definitely help you out replace the whole node module, remember one thing when you extract there will be node_module inside node_module so copy the second node module folder with all the files like I can say either extract in another directory and directly copy in your node module location: https://drive.google.com/file/d/1FwqodHIRIedyb_Z3s8os53UfLDxqB5AL/view?usp=sharing
Let me know if this helps :)
I have made it worked several times, let me know if anyone gets any issue.

**Comment by anikchowdhury1** [comment]
> Guys the workaround is instead of replacing the api.zip replace in the node module, here is the directory that I have used and it will definitely help you out replace the whole node module, remember one thing when you extract there will be node_module inside node_module so copy the second node module folder with all the files like I can say either extract in another directory and directly copy in your node module location: https://drive.google.com/file/d/1FwqodHIRIedyb_Z3s8os53UfLDxqB5AL/view?usp=sharing
> Let me know if this helps :)
> I have made it worked several times, let me know if anyone gets any issue.

@SJ029626 , are you able to download youtube videos? using this modules I can download everything expect youtube videos.

**Comment by SJ029626** [comment]
@nikitow1 yes there is a dll file which is missing from system32 folder in c drive on your side if X32 architecture otherwise from syswow64 if x64 architecture and that file is this: https://www.dll-files.com/msvcr100.dll.html . You can download from here.

**Comment by anikchowdhury1** [comment]
> @nikitow1 yes there is a dll file which is missing from system32 folder in c drive on your side if X32 architecture otherwise from syswow64 if x64 architecture and that file is this: https://www.dll-files.com/msvcr100.dll.html . You can download from here.

@SJ029626 oh! I am mac user, I am not using windows.

**Comment by SJ029626** [comment]
> > @nikitow1 yes there is a dll file which is missing from system32 folder in c drive on your side if X32 architecture otherwise from syswow64 if x64 architecture and that file is this: https://www.dll-files.com/msvcr100.dll.html . You can download from here.
> 
> @SJ029626 oh! I am mac user, I am not using windows.

@nikitow1 still there is a file missing and that is the reason of videos not being getting downloaded. check for the mac thing and post it here if worked out for you :)
I debugged the whole part and found it out.

**Comment by fmorelli89** [comment]
From original Repository you have to update api and youtube downloader.
Use docker image for remove platform-dependence

docker pull udacimak/udacimak

lunch with: 
docker container run --rm -it -v "$(pwd)/:/downloads" --entrypoint /bin/bash udacimak/udacimak 

inside the container's cli you have to update api code

apt-get update
apt-get install wget unzip
wget https://github.com/udacimak/udacimak/files/6087914/api.zip
#overwrite, with prompt
unzip api.zip -d /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/lib/api/ 


#update youtube-dl
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl
chmod a+rx /usr/local/nvm/versions/node/v11.1.0/lib/node_modules/udacimak/node_modules/youtube-dl/bin/youtube-dl

#Finish !

References:
How to Use https://github.com/udacimak/udacimak/wiki/How-to-Use
New API https://github.com/udacimak/udacimak/issues/192 
Youtybe DL https://github.com/ytdl-org/youtube-dl#installation

**Comment by Ngai-E** [comment]
> Hi guys replace the files in your ~\node_modules\udacimak\lib\api folder with these files ([api.zip](https://github.com/udacimak/udacimak/files/6087914/api.zip)). You will have to find a way to locate your node modules folder as it differs for most systems. I made changes to the code and they work fine for me. You can first make a backup of your old files before replacing.

works like a charm

**Comment by Ngai-E** [comment]
> hey @amoat7, can you please provide us any hint on how to install udacimak, as it's not installing any more?
> 
> ![image](https://user-images.githubusercontent.com/24620184/116125064-f76b5100-a6bc-11eb-9aa7-79c310f93b3d.png)

**Comment by Ngai-E** [comment]
@GhaziXX I had same issues. I updated my npm and node versions then reinstalled youtube-dl (I set my default python version for npm to be 2.7 with this command `npm config set python python2.7` before reinstalling. Feel free to run the steps with any version >=2.7, though for some reason mine was failing) finally installed udacimak like this `npm install -g udacimak --force`.

**Comment by fisal77** [comment]
Fixed #192 - by @amoat7 - https://github.com/udacimak/udacimak/issues/192#issuecomment-791117453

**Comment by alihussainia** [comment]
@amoat7 You can use `npm root -g` command to find the path to the node_modules directory =)

**Comment by ryan-efendy** [comment]
@amoat7 thank u 🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by gillmoni** [comment]
I still cannot login via udacimak login or settoken <TOKEN> tried Windows and WSL both (with api.zip replacement and google drive link shared above).
Any help would be appreciated
![2022-08-06_21h57_231](https://user-images.githubusercontent.com/871383/183271839-355eb3b9-6576-4188-919a-dfd9ecc54d50.png)

**Comment by Tarek-Bohdima** [comment]
here is the fix that helped me https://github.com/udacimak/udacimak/pull/230#issuecomment-1233143089
